apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-${env}
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-${env}
  targetNamespace: env-${env}
  chart:
    spec:
      chart: vcluster-eks
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  install:
    createNamespace: true
  values:
    syncer:
      extraArgs:
        - --tls-san=env-${env}.env-${env}.svc.cluster.local
        - --out-kube-config-server=https://env-${env}.env-${env}.svc.cluster.local
