apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- env-dev.yaml
#- env-prod.yaml
#- env-qa.yaml
- helm-repository.yaml
- vluster-dev.yaml
- vluster-prod.yaml
- vluster-qa.yaml
