apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-qa
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true # remove stale resources from cluster
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./vcluster-template"
  wait: true
  postBuild:
    substitute:
      env: qa