apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-qa
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-qa
  targetNamespace: env-qa
  wait: true
  chart:
    spec:
      chart: vcluster-eks
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  install:
    createNamespace: true
  values:
    syncer:
      extraArgs:
        - --tls-san=env-qa.env-qa.svc.cluster.local
        - --out-kube-config-server=https://env-qa.env-qa.svc.cluster.local
