apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loft-sh
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.loft.sh
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-dev
  namespace: flux-system
spec:
  interval: 1m
  releaseName: env-dev
  targetNamespace: env-dev
  chart:
    spec:
      chart: vcluster-eks
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: loft-sh
  install:
    createNamespace: true
